version: "2"
services:
  db:
    image: postgres:14.1-alpine
    environment:
      - POSTGRES_DB=ledit
      - POSTGRES_USER=dbuser
      - POSTGRES_PASSWORD=password
    ports:
      - "9433:5432"

