name: CI
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
env:
  SQLX_OFFLINE: true

jobs:
  telegram_message_ci_start:
      name: Telegram Message on CI Start
      runs-on: ubuntu-latest
      steps:
        - name: send message
          uses: appleboy/telegram-action@master
          with:
            to: ${{ secrets.TELEGRAM_TO }}
            token: ${{ secrets.TELEGRAM_TOKEN }}
            args: 💬🔨 GitHub actions started CI jobs for ledit.

  check_formatting:
    name: "Check Formatting"
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@master
      - name: install rust
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: nightly
          components: rustfmt
          override: true
      - name: cargo fmt
        run: |
          cargo fmt --all -- --check

  clippy:
    name: "Clippy"
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@master
      - name: install rust
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: nightly
          components: clippy
          override: true
      - name: cargo clippy
        run: |
          cargo clippy -- --D warnings

  build_and_publish:
    name: Build and Publish
    if: github.ref == 'refs/heads/main'
    needs: [clippy, check_formatting]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1 
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.PACKAGES }}
      - name: Get short commit hash for image tag
        id: shortened_hash
        run: echo "::set-output name=sha_short::$(git rev-parse --short HEAD)"
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          platforms: linux/amd64
          push: true
          tags: |
            ghcr.io/jflessau/ledit:latest
            ghcr.io/jflessau/ledit:${{ steps.shortened_hash.outputs.sha_short }}

  telegram_build_and_publish_notification:
    name: Send Telegram Notification
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    needs: [build_and_publish]
    steps:
      - name: Get short commit hash for image tag
        id: shortened_hash
        run: echo "::set-output name=sha_short::$(git rev-parse --short HEAD)"
      - name: Send Telegram Notification
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_TO }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          args: 🐳 GitHub actions published image for ledit.